# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4291fd1867aaecca2934f216782eec50a943684cfc2b9b88a9e5000dace050edcccabc43db029a1123e7c994d32ff1f017a50cf1f78bbd1736f622ee532cbf

test:
  secret_key_base: 3915961fe1eb3599be1529bfc0fc02b3c19e9cb105517dfd2688535fcfeecbc4666650a39c3cb0e7fc0debf32c4a6186dd9ae14b2c3dd64f90eaabce402bad02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
